Feat/put products
devBK84/Food-Delivery-App pull request #32
Opened 2023-01-08 11:46 UTC by devBK84

2023-01-08 13:44 UTC, MoinMarcell requested changes
LGTM, I mentioned some changes and check your language. You mix up english and german, choose one language :) And also check you codesmell in the sonar comment for backend

2023-01-08 13:44 UTC, MoinMarcell commented on backend/src/main/java/com/github/devbk84/backend/controller/ProductController.java
> +        return productService.getProductsById(id);
You just recive one product, you should rename the methods to getProductById 
```suggestion
    public Product getProductById(@PathVariable String id){
        return productService.getProductById(id);
```

2023-01-08 13:44 UTC, MoinMarcell commented on backend/src/main/java/com/github/devbk84/backend/service/ProductService.java
> +    public Product getProductsById(String id) {
As mentioned above, you get one produtc, not many :)
```suggestion
    public Product getProductById(String id) {
```

2023-01-08 13:44 UTC, MoinMarcell commented on backend/src/test/java/com/github/devbk84/backend/controller/ProductControllerTest.java
> +    void getProductsById() throws Exception {
```suggestion
    void getProductById() throws Exception {
```

2023-01-08 13:44 UTC, MoinMarcell commented on backend/src/test/java/com/github/devbk84/backend/controller/ProductControllerTest.java
> +                .andExpect(status().isOk());
For later it is easier to seperate the product in a own Variable, so you can easily modify the test later :)
```suggestion
        Product product = new Product("69",
                "Milch", "Test",
                "orderFav", new BigDecimal(0));
        productRepo.save(product);
        mockMvc.perform(get("/api/products/" + product.id()))
                .andExpect(status().isOk());
```

2023-01-09 10:40 UTC, fannie-id approved these changes

2023-01-09 10:42 UTC, fannie-id approved these changes

2023-01-09 10:43 UTC, merged